/**
 * Color ranges generated by Smart Swatch
 *
 * @see https://smart-swatch.netlify.app/
 */
export const colors = {
    idap: {
      blue: { value: '#0b1e41' },
      yellow: { value: '#f4a224' },
      clickable: { value: '#f4a224' }, // idapYellow
      lightText: { value: '#cddae5' }, // idapLtGrey.100
      highlight: { value: '#C3FEC0' },
      accent1: { value: '#bb2b40' }, // idapRed
      accent2: { value: '#92a6ba' }, // idapLtGrey
      accent3: { value: '#7a8e9f' } // idapDkGrey
    },
    idapBlue: {
      50: { value: '#e6f0ff' },
      100: { value: '#bed1f4' },
      200: { value: '#94b2e9' },
      300: { value: '#6b93e1' },
      400: { value: '#4275d8' },
      500: { value: '#2b5bbf' }, // start using white text here
      600: { value: '#214795' },
      700: { value: '#17336b' },
      800: { value: '#0b1e41' }, // IDAP Blue
      900: { value: '#010a1a' }
    },
    idapBlueAlpha: {
      50: { value: 'rgba(13, 35, 75, 0.04)' },
      100: { value: 'rgba(13, 35, 75, 0.06)' },
      200: { value: 'rgba(13, 35, 75, 0.08)' },
      300: { value: 'rgba(13, 35, 75, 0.16)' },
      400: { value: 'rgba(13, 35, 75, 0.24)' },
      500: { value: 'rgba(13, 35, 75, 0.36)' },
      600: { value: 'rgba(13, 35, 75, 0.48)' },
      700: { value: 'rgba(13, 35, 75, 0.64)' },
      800: { value: 'rgba(13, 35, 75, 0.80)' }, // backdrop
      900: { value: 'rgba(13, 35, 75, 0.92)' }
    },
    idapYellow: {
      50: { value: '#fff4dc' },
      100: { value: '#fde0b1' },
      200: { value: '#facc82' },
      300: { value: '#f7b753' },
      400: { value: '#f4a224' }, // IDAP Yellow
      500: { value: '#db890b' },
      600: { value: '#aa6a05' },
      700: { value: '#7b4c02' }, // start using white text here
      800: { value: '#4a2d00' },
      900: { value: '#1d0e00' }
    },
    idapRed:  {
      50: { value: '#ffe6ec' },
      100: { value: '#f6bfc7' },
      200: { value: '#e996a3' },
      300: { value: '#df6d7e' },
      400: { value: '#d4445a' },
      500: { value: '#bb2b40' }, // IDAP Red, start using white text here
      600: { value: '#922032' },
      700: { value: '#6a1623' },
      800: { value: '#410a14' },
      900: { value: '#1d0005' }
    },
    idapLtGrey: {
      50: { value: '#e8f3fe' },
      100: { value: '#cddae5' },
      200: { value: '#b0c0cf' },
      300: { value: '#92a6ba' }, // IDAP Accent #2
      400: { value: '#748da5' },
      500: { value: '#5a738b' }, // start using white text here
      600: { value: '#455a6d' },
      700: { value: '#30404f' },
      800: { value: '#1b2632' },
      900: { value: '#020e17' },
    },
    idapDkGrey: {
      50: { value: '#e8f3ff' },
      100: { value: '#cfdae4' },
      200: { value: '#b3c0cb' },
      300: { value: '#97a7b5' },
      400: { value: '#7a8e9f' }, // IDAP Accent #3
      500: { value: '#607585' }, // start using white here
      600: { value: '#4a5b68' },
      700: { value: '#34414c' },
      800: { value: '#1b2830' },
      900: { value: '#010e18' },
    }
}